sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: ewq/.,321hf/.,
  alioss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    access-key-id: LTAI5tLfzsoq9qfRmS6kknsK
    access-key-secret: 9AwyQYnKJusbemuUxK86rM8fHzjPUF
    bucket-name: sky-hfhf
  redis:
    host: localhost
    port: 6379
    password: "123456"
    database: 10
  wechat:
    appid: wx6aa3649e18a6b14e
    secret: d03577a6c0d523600fc6874f6ff1a054